# Numpy Assignment 1
---
Submitted by: **Uzair Aziz Suria**


Roll#: **PIAIC148047**

<!-- <hr style={
    border: none;
    border-top:1px dashed red;
    width: 100%;
    height: 1px
    }/> -->
    
<div style='border-top: red 2px dotted'/>

## Section 1
Difficulty Level: **Beginner**

**1.**

Import the numpy package under the name np

In [1]:
import numpy as np

**2.**

Create a null vector of size 10 

In [2]:
null_10 = np.zeros(10)

In [3]:
null_10

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

**3.**

Create a vector with values ranging from 10 to 49

In [4]:
arr1 = np.arange(10, 50)
arr1

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

**4.**

Find the shape of previous array in question 3

In [5]:
np.shape(arr1)

(40,)

**5.**

Print the type of the previous array in question 3

In [6]:
arr1.dtype

dtype('int32')

**6.**

Print the numpy version and the configuration


In [7]:
print(f"Numpy Version: {np.__version__}")
print(f"Numpy Config: {np.show_config()}")

Numpy Version: 1.19.2
blas_mkl_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/uzair/machine-learning/PIAIC/AI/env\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:/Users/uzair/machine-learning/PIAIC/AI/env\\Library\\include']
blas_opt_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/uzair/machine-learning/PIAIC/AI/env\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:/Users/uzair/machine-learning/PIAIC/AI/env\\Library\\include']
lapack_mkl_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/uzair/machine-learning/PIAIC/AI/env\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:/Users/uzair/machine-learning/PIAIC/AI/env\\Library\\include']
lapack_opt_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/uzair/machine-learning/PIAIC/AI/env\\Library\\lib']
    define_macros = [(

**7.**

Print the dimension of the array in question 3


In [8]:
arr1.ndim

1

**8.**

Create a boolean array with all the True values

In [9]:
arr2 = np.ones(5, dtype=bool)

In [10]:
arr2

array([ True,  True,  True,  True,  True])

**9.**

Create a two dimensional array




In [11]:
arr3 = np.array([[1, 2, 3],
                 [4, 5, 6]])
arr3

array([[1, 2, 3],
       [4, 5, 6]])

**10.**

Create a three dimensional array



In [12]:
arr4 = np.array([[[1, 2, 3], [4, 5, 6]],[[7, 8, 9], [10, 11, 12]]])
arr4

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

**11.**

Reverse a vector (first element becomes last)

In [13]:
np.flip(arr4)

array([[[12, 11, 10],
        [ 9,  8,  7]],

       [[ 6,  5,  4],
        [ 3,  2,  1]]])

12. Create a null vector of size 10 but the fifth value which is 1 

In [14]:
arr5 = np.zeros(10, dtype=int)
arr5[4] = 1
arr5

array([0, 0, 0, 0, 1, 0, 0, 0, 0, 0])

**13.**

Create a 3x3 identity matrix

In [15]:
arr6 = np.ones(9).reshape(3,3)
arr6

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

**14.**

```python
arr = np.array([1, 2, 3, 4, 5])
```

---

 Convert the data type of the given array from int to float 

In [16]:
arr7  =np.array([1, 2, 3, 4, 5])
arr7 = arr7.astype(float)
arr7

array([1., 2., 3., 4., 5.])

**15.**


```python
arr1 = np.array([[1., 2., 3.],
                 [4., 5., 6.]])  
                      
arr2 = np.array([[0., 4., 1.],
                 [7., 2., 12.]])
```
---


Multiply arr1 with arr2


In [17]:
arr8 = np.array([[1., 2., 3.],
                 [4., 5., 6.]])
arr9 = np.array([[0., 4., 1.],
                 [7, 2, 12.]])
res = np.multiply(arr8, arr9)
res

array([[ 0.,  8.,  3.],
       [28., 10., 72.]])

**16.**


```python
arr1 = np.array([[1., 2., 3.],
                 [4., 5., 6.]])               
arr2 = np.array([[0., 4., 1.], 
                 [7., 2., 12.]])
```

---

Make an array by comparing both the arrays provided above

In [18]:
arr10 = np.array([[1., 2., 3.],
                 [4., 5., 6.]]) 

arr11 = np.array([[0., 4., 1.],
                 [7., 2., 12.]])

In [19]:
comp = (arr10 >= arr11)
comp

array([[ True, False,  True],
       [False,  True, False]])

**17.**

Extract all odd numbers from arr with values(0-9)

In [20]:
arr12 = np.arange(0, 10)
arr12

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [21]:
odd_array=arr12[arr12%2!=0]
odd_array

array([1, 3, 5, 7, 9])

**18.**

Replace all odd numbers to -1 from previous array

In [22]:
replaced_array = arr12
replaced_array[replaced_array%2!=0]=-1
replaced_array

array([ 0, -1,  2, -1,  4, -1,  6, -1,  8, -1])

**19.**

```python
arr = np.arange(10)
```

---

Replace the values of indexes 5,6,7 and 8 to **12**

In [23]:
arr13 = np.arange(10)
arr13[5:9]=12
arr13

array([ 0,  1,  2,  3,  4, 12, 12, 12, 12,  9])

**20.**

Create a 2d array with 1 on the border and 0 inside

In [24]:
arr14 = np.ones((5,5), dtype=int)
arr14[1:-1, 1:-1] = 0
arr14

array([[1, 1, 1, 1, 1],
       [1, 0, 0, 0, 1],
       [1, 0, 0, 0, 1],
       [1, 0, 0, 0, 1],
       [1, 1, 1, 1, 1]])

## Section 2
Difficulty Level: **Medium**

**21.**
```python
arr2d = np.array([[1, 2, 3],
                  [4, 5, 6], 
                  [7, 8, 9]])
```
---

Replace the value 5 to 12

In [25]:
arr2d = np.array([[1, 2, 3],
                  [4, 5, 6],
                  [7, 8, 9]])

arr2d[1, 1]=12
arr2d

array([[ 1,  2,  3],
       [ 4, 12,  6],
       [ 7,  8,  9]])

**22.**

```python
arr3d = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
```
---
Convert all the values of 1st array to 64


In [26]:
arr3d = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
arr3d[0, 0] = 64
arr3d

array([[[64, 64, 64],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

**23.**

Make a 2-Dimensional array with values 0-9 and slice out the first 1st 1-D array from it

In [27]:
arr15 = np.arange(10).reshape(2, 5)
arr15[0:1, :]

array([[0, 1, 2, 3, 4]])

**24.**

Make a 2-Dimensional array with values 0-9 and slice out the 2nd value from 2nd 1-D array from it

In [28]:
arr16 = np.arange(10).reshape(2, 5)
arr16[1:, 1:2]

array([[6]])

**25.**

Make a 2-Dimensional array with values 0-9 and slice out the third column but only the first two rows

In [29]:
arr17 = np.arange(10).reshape(2, 5)
arr17
arr17[:3, 2:3]

array([[2],
       [7]])

**26.**

Create a 10x10 array with random values and find the minimum and maximum values

In [30]:
arr18 = np.random.rand(10*10).reshape(10, 10)

In [31]:
arr18

array([[0.17248859, 0.32748828, 0.35955486, 0.618566  , 0.09901152,
        0.71910442, 0.48493161, 0.57119774, 0.99251958, 0.98665454],
       [0.93151237, 0.17534721, 0.80830831, 0.70996862, 0.24069527,
        0.1725291 , 0.80873639, 0.25449757, 0.64300465, 0.57624754],
       [0.10831982, 0.26487206, 0.0410613 , 0.33880797, 0.97878775,
        0.19959976, 0.85233658, 0.71407122, 0.25253146, 0.67180518],
       [0.42835152, 0.18417303, 0.72639528, 0.03623342, 0.13254671,
        0.43761441, 0.52176588, 0.02412069, 0.36321255, 0.8896228 ],
       [0.99672803, 0.48732351, 0.0115459 , 0.53349143, 0.69972261,
        0.53072738, 0.86994886, 0.90690956, 0.270935  , 0.30260627],
       [0.74733612, 0.27807063, 0.4979147 , 0.80268319, 0.08115284,
        0.63866751, 0.30898366, 0.3036567 , 0.31477977, 0.65286233],
       [0.41782769, 0.99495222, 0.97128416, 0.35477171, 0.1047406 ,
        0.05176018, 0.07092196, 0.86980226, 0.0225731 , 0.11485005],
       [0.50307711, 0.18831027, 0.1098317

In [32]:
arr18.max()

0.9967280277203657

In [33]:
arr18.min()

0.006761574700202333

**27.**

```python
a = np.array([1,2,3,2,3,4,3,4,5,6]) b = np.array([7,2,10,2,7,4,9,4,9,8])
```

---
Find the common items between a and b


In [34]:
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])

In [35]:
np.intersect1d(a, b)

array([2, 4])

**28.**
```python
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])
```


---
Find the positions where elements of a and b match



In [36]:
np.equal(a, b).nonzero()[0]

array([1, 3, 5, 7], dtype=int64)

**29.**

```python
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])
data = np.random.randn(7, 4)
```

---
Find all the values from array **data** where the values from array **names** are not equal to **Will**


In [37]:
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])
data = np.random.randint(4, size=7)
print(f"Data: {data}")
# data[(names[data] != "Will").nonzero()]
data_filtered = []
for i in range(len(names)):
    if names[i] != "Will":
        data_filtered.append(data[i])
print(f"Filtered Data: {data_filtered}")

Data: [1 1 3 1 1 0 1]
Filtered Data: [1, 1, 1, 0, 1]


**30.**
```python
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe']) data = np.random.randn(7, 4)
```
---
Find all the values from array **data** where the values from array **names** are not equal to **Will** and **Joe**



In [38]:
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])
data = np.random.randint(4, size=7)
print(f"Data: {data}")
# data[(names[data] != "Will").nonzero()]
data_filtered = []
for i in range(len(names)):
    if names[i] != "Will" and names[i]!="Joe":
        data_filtered.append(data[i])
print(f"Filtered Data: {data_filtered}")

Data: [0 0 1 3 2 2 2]
Filtered Data: [0, 3]


## Section 3
Difficulty Level **Hard**

**31.**

Create a 2D array of shape 5x3 to contain decimal numbers between 1 and 15.

In [39]:
arr19 = np.arange(1, 16, dtype=float).reshape(5, 3)
arr19

array([[ 1.,  2.,  3.],
       [ 4.,  5.,  6.],
       [ 7.,  8.,  9.],
       [10., 11., 12.],
       [13., 14., 15.]])

**32.**

Create an array of shape (2, 2, 4) with decimal numbers between 1 to 16.

In [40]:
arr20 = np.arange(1, 17, dtype=float).reshape(2, 2, 4)
arr20

array([[[ 1.,  2.,  3.,  4.],
        [ 5.,  6.,  7.,  8.]],

       [[ 9., 10., 11., 12.],
        [13., 14., 15., 16.]]])

**33.**

Swap axes of the array you created in Question 32

In [41]:
np.swapaxes(arr20, 1, 2)

array([[[ 1.,  5.],
        [ 2.,  6.],
        [ 3.,  7.],
        [ 4.,  8.]],

       [[ 9., 13.],
        [10., 14.],
        [11., 15.],
        [12., 16.]]])

**34.**

Create an array of size 10, and find the square root of every element in the array, if the values less than 0.5, replace them with 0

In [42]:
arr21 = np.random.uniform(0, 1, 10)
# arr21
arr21sqrt = np.sqrt(arr21)
for i in range(len(arr21sqrt)):
    if arr21sqrt[i] < 0.5:
        arr21sqrt[i] = 0
arr21sqrt

array([0.98105411, 0.        , 0.59031664, 0.        , 0.70924454,
       0.71133246, 0.6471077 , 0.        , 0.        , 0.        ])

**35.**

Create two random arrays of range 12 and make an array with the maximum values between each element of the two arrays

In [43]:
arr22 = np.random.uniform(0, 5, size=12)
arr23 = np.random.uniform(0, 5, size=12)
arr24 = np.maximum(arr22, arr23)
arr24

array([3.42977501, 1.97177169, 3.39544351, 3.45055523, 2.32295769,
       2.5632972 , 3.63929981, 4.93463148, 4.62394532, 4.21441591,
       3.90371379, 3.26201938])

**36.**

```python
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])
```
---
Find the unique names and sort them out!


In [44]:
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])
np.sort(np.unique(names))

array(['Bob', 'Joe', 'Will'], dtype='<U4')

**37.**
```python
a = np.array([1,2,3,4,5])
b = np.array([5,6,7,8,9])
```
---
From array a remove all items present in array b



In [45]:
a = np.array([1,2,3,4,5])
b = np.array([5,6,7,8,9])

np.setdiff1d(a, b)

array([1, 2, 3, 4])

**38.**

Following is the input NumPy array delete column two and insert following new column in its place.

---
```python
sampleArray = numpy.array([[34,43,73],[82,22,12],[53,94,66]]) 
newColumn = numpy.array([[10,10,10]])
```
---

In [46]:
sampleArray = np.array([[34,43,73],[82,22,12],[53,94,66]]) 
newColumn = np.array([[10,10,10]])

newSampleArray = sampleArray
newSampleArray[1:2, :] = newColumn
newSampleArray

array([[34, 43, 73],
       [10, 10, 10],
       [53, 94, 66]])

**39.**

```python
x = np.array([[1., 2., 3.], [4., 5., 6.]])
y = np.array([[6., 23.], [-1, 7], [8, 9]])
```

---
Find the dot product of the above two matrix


In [47]:
x = np.array([[1., 2., 3.], [4., 5., 6.]])
y = np.array([[6., 23.], [-1, 7], [8, 9]])
np.dot(x, y)

array([[ 28.,  64.],
       [ 67., 181.]])

**40.**

Generate a matrix of 20 random values and find its cumulative sum

In [48]:
np.cumsum(np.random.uniform(0, 5, 20))

array([ 4.31935345,  4.48751968,  4.65183405,  8.24870508, 12.36980692,
       16.37743495, 16.83488248, 17.68585386, 19.27672319, 20.79818052,
       21.66987287, 26.35551887, 31.13385838, 35.66571668, 38.42908105,
       40.20809917, 40.70111713, 43.4939486 , 44.81703662, 47.57916694])