# Numpy Assignment 2
---
Submitted by: **Uzair Aziz Suria**


Roll#: **PIAIC148047**

<!-- <hr style={
    border: none;
    border-top:1px dashed red;
    width: 100%;
    height: 1px
    }/> -->
    
<div style='border-top: red 2px dotted'/>

## Question:1

### Convert a 1D array to a 2D array with 2 rows?

#### Desired output

```python
array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])
```

In [1]:
import numpy as np
np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9]).reshape(2, 5)

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

## Question:2

###  How to stack two arrays vertically?

#### Desired Output::

```python
array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])
```

In [2]:
a = np.arange(0, 10, 1).reshape(2, 5)
b = np.ones(10, dtype=int).reshape(2, 5)
np.vstack((a, b))

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

## Question:3

### How to stack two arrays horizontally?

#### Desired Output::

```python
array([[0, 1, 2, 3, 4, 1, 1, 1, 1, 1],
       [5, 6, 7, 8, 9, 1, 1, 1, 1, 1]])
```

In [3]:
np.hstack((a.reshape(2, 5), b.reshape(2, 5)))

array([[0, 1, 2, 3, 4, 1, 1, 1, 1, 1],
       [5, 6, 7, 8, 9, 1, 1, 1, 1, 1]])

## Question:4

### How to convert an array of arrays into a flat 1d array?

#### Desired Output::

In [4]:
np.ravel(np.array([[0, 1, 2, 3, 4], [5, 6, 7, 8, 9]]))

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

## Question:5

### How to Convert higher dimension into one dimension?

#### Desired Output::

In [5]:
array2d = np.arange(0, 15).reshape(3, 5)
print(f"Original Array:\n{array2d}")
print ("\nResult:")
array2d.flatten()

Original Array:
[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]

Result:


array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

## Question:6

### Convert one dimension to higher dimension?

#### Desired Output::

```python
array([[ 0, 1, 2],
       [ 3, 4, 5],
       [ 6, 7, 8],
       [ 9, 10, 11],
       [12, 13, 14]])
```

In [6]:
array1d = np.arange(0, 15)
print(array1d)
array1d.reshape(5, 3)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]


array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])

## Question:7

### Create a 5x5 array and find the square of an array?

In [7]:
array5x5 = np.random.rand(5, 5)
np.square(array5x5)

array([[0.90018503, 0.25787417, 0.00919708, 0.62273378, 0.54220542],
       [0.61611728, 0.30556081, 0.65500065, 0.39811996, 0.84643119],
       [0.26692904, 0.49323774, 0.00311464, 0.81826168, 0.58558829],
       [0.25756198, 0.05428314, 0.40848852, 0.79830928, 0.64433844],
       [0.79032676, 0.69160618, 0.71243763, 0.07099704, 0.06538341]])

## Question:8

### Create 5x6 an array and find the mean?

In [8]:
array5x6 = np.random.rand(5, 6)
np.mean(array5x6)

0.5789273406360558

## Question:9

### Find the standard deviation of the previous array in Q8?

In [9]:
np.std(array5x6)

0.29291950615601103

## Question:10

### Find the median of the previous array in Q8?

In [10]:
np.median(array5x6)

0.602004412874465

## Question:11

### Find the transpose of the previous array in Q8?

In [11]:
array5x6.T

array([[0.41944111, 0.87784406, 0.78770902, 0.94485204, 0.00386123],
       [0.9930678 , 0.20536818, 0.95476691, 0.43030145, 0.47047065],
       [0.89851537, 0.19045499, 0.77046253, 0.71361265, 0.28123929],
       [0.27583341, 0.96972683, 0.59610334, 0.93072638, 0.60790549],
       [0.23374248, 0.46292809, 0.70137667, 0.81615261, 0.83237728],
       [0.85485367, 0.3551118 , 0.27491598, 0.30681674, 0.2072822 ]])

## Question:12

### Create a 4x4 an array and find the sum of diagonal elements?

In [12]:
array4x4 = np.random.rand(4, 4)
print(array4x4)
np.trace(array4x4)

[[0.08614609 0.8000481  0.71119625 0.02999347]
 [0.35146669 0.17769783 0.06110384 0.21996997]
 [0.35175718 0.28142582 0.30654244 0.97648826]
 [0.98263004 0.42013989 0.54863093 0.18695554]]


0.7573418985015897

## Question:13

### Find the determinant of the previous array in Q12?

In [13]:
np.linalg.det(array4x4)

0.10772787367594905

## Question:14

### Find the 5th and 95th percentile of an array?

In [14]:
exArray = np.random.randint(25, 100, (4, 4))
print(f"5th Percentile: {np.percentile(exArray, 5)}")
print(f"95th Percentile: {np.percentile(exArray, 95)}")

5th Percentile: 38.5
95th Percentile: 97.25


## Question:15

### How to find if a given array has any null values?

In [15]:
arrayWithNaN = np.array([
    [5, np.nan, 8],
    [2, 0, 1]
])
arrayWithNaN

array([[ 5., nan,  8.],
       [ 2.,  0.,  1.]])

In [16]:
np.isnan(arrayWithNaN).any()

True