# **Assignment For Numpy**

Difficulty Level **Beginner**

1. Import the numpy package under the name np

In [1]:
import numpy as np

2. Create a null vector of size 10 

In [2]:
null_10 = np.zeros(10)

In [3]:
null_10

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

3. Create a vector with values ranging from 10 to 49

In [6]:
arr1 = np.arange(10, 50)
arr1

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

4. Find the shape of previous array in question 3

In [7]:
np.shape(arr1)

(40,)

5. Print the type of the previous array in question 3

In [10]:
arr1.dtype

dtype('int32')

6. Print the numpy version and the configuration


In [16]:
print(f"Numpy Version: {np.__version__}")
print(f"Numpy Config: {np.show_config()}")

Numpy Version: 1.19.2
blas_mkl_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/uzair/machine-learning/PIAIC/AI/env\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:/Users/uzair/machine-learning/PIAIC/AI/env\\Library\\include']
blas_opt_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/uzair/machine-learning/PIAIC/AI/env\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:/Users/uzair/machine-learning/PIAIC/AI/env\\Library\\include']
lapack_mkl_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/uzair/machine-learning/PIAIC/AI/env\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:/Users/uzair/machine-learning/PIAIC/AI/env\\Library\\include']
lapack_opt_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/uzair/machine-learning/PIAIC/AI/env\\Library\\lib']
    define_macros = [(

7. Print the dimension of the array in question 3


In [20]:
arr1.ndim

1

8. Create a boolean array with all the True values

In [25]:
arr2 = np.ones(5, dtype=bool)

In [26]:
arr2

array([ True,  True,  True,  True,  True])

9. Create a two dimensional array




In [28]:
arr3 = np.array([[1, 2, 3],
                 [4, 5, 6]])
arr3

array([[1, 2, 3],
       [4, 5, 6]])

10. Create a three dimensional array



In [31]:
arr4 = np.array([[[1, 2, 3], [4, 5, 6]],[[7, 8, 9], [10, 11, 12]]])
arr4

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

Difficulty Level **Easy**

11. Reverse a vector (first element becomes last)

In [35]:
np.flip(arr4)

array([[[12, 11, 10],
        [ 9,  8,  7]],

       [[ 6,  5,  4],
        [ 3,  2,  1]]])

12. Create a null vector of size 10 but the fifth value which is 1 

In [39]:
arr5 = np.zeros(10, dtype=int)
arr5[4] = 1
arr5

array([0, 0, 0, 0, 1, 0, 0, 0, 0, 0])

13. Create a 3x3 identity matrix

In [40]:
arr6 = np.ones(9).reshape(3,3)
arr6

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

14. arr = np.array([1, 2, 3, 4, 5]) 

---

 Convert the data type of the given array from int to float 

In [43]:
arr7  =np.array([1, 2, 3, 4, 5])
arr7 = arr7.astype(float)
arr7

array([1., 2., 3., 4., 5.])

15. arr1 =          np.array([[1., 2., 3.],

                    [4., 5., 6.]])  
                      
    arr2 = np.array([[0., 4., 1.],
     
                   [7., 2., 12.]])

---


Multiply arr1 with arr2


In [45]:
arr8 = np.array([[1., 2., 3.],
                 [4., 5., 6.]])
arr9 = np.array([[0., 4., 1.],
                 [7, 2, 12.]])
res = np.multiply(arr8, arr9)
res

array([[ 0.,  8.,  3.],
       [28., 10., 72.]])

16. arr1 = np.array([[1., 2., 3.],
                    [4., 5., 6.]]) 
                    
    arr2 = np.array([[0., 4., 1.], 
                    [7., 2., 12.]])


---

Make an array by comparing both the arrays provided above

In [49]:
arr10 = np.array([[1., 2., 3.],
                 [4., 5., 6.]]) 

arr11 = np.array([[0., 4., 1.],
                 [7., 2., 12.]])

In [52]:
comp = (arr10 >= arr11)
comp

array([[ True, False,  True],
       [False,  True, False]])

17. Extract all odd numbers from arr with values(0-9)

In [53]:
arr12 = np.arange(0, 10)
arr12

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [55]:
odd_array=arr12[arr12%2!=0]
odd_array

array([1, 3, 5, 7, 9])

18. Replace all odd numbers to -1 from previous array

In [56]:
replaced_array = arr12
replaced_array[replaced_array%2!=0]=-1
replaced_array

array([ 0, -1,  2, -1,  4, -1,  6, -1,  8, -1])

19. arr = np.arange(10)


---

Replace the values of indexes 5,6,7 and 8 to **12**

In [60]:
arr13 = np.arange(10)
arr13[5:9]=12
arr13

array([ 0,  1,  2,  3,  4, 12, 12, 12, 12,  9])

20. Create a 2d array with 1 on the border and 0 inside

In [64]:
arr14 = np.ones((5,5), dtype=int)
arr14[1:-1, 1:-1] = 0
arr14

array([[1, 1, 1, 1, 1],
       [1, 0, 0, 0, 1],
       [1, 0, 0, 0, 1],
       [1, 0, 0, 0, 1],
       [1, 1, 1, 1, 1]])

Difficulty Level **Medium**

21. arr2d = np.array([[1, 2, 3],

                    [4, 5, 6], 

                    [7, 8, 9]])

---

Replace the value 5 to 12

In [65]:
arr2d = np.array([[1, 2, 3],
                  [4, 5, 6],
                  [7, 8, 9]])

arr2d[1, 1]=12
arr2d

array([[ 1,  2,  3],
       [ 4, 12,  6],
       [ 7,  8,  9]])

22. arr3d = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

---
Convert all the values of 1st array to 64


In [69]:
arr3d = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
arr3d[0, 0] = 64
arr3d

array([[[64, 64, 64],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

23. Make a 2-Dimensional array with values 0-9 and slice out the first 1st 1-D array from it

In [74]:
arr15 = np.arange(10).reshape(2, 5)
arr15[0:1, :]

array([[0, 1, 2, 3, 4]])

24. Make a 2-Dimensional array with values 0-9 and slice out the 2nd value from 2nd 1-D array from it

In [76]:
arr16 = np.arange(10).reshape(2, 5)
arr16[1:, 1:2]

array([[6]])

25. Make a 2-Dimensional array with values 0-9 and slice out the third column but only the first two rows

In [82]:
arr17 = np.arange(10).reshape(2, 5)
arr17
arr17[:3, 2:3]

array([[2],
       [7]])

26. Create a 10x10 array with random values and find the minimum and maximum values

In [85]:
arr18 = np.random.rand(10*10).reshape(10, 10)

In [86]:
arr18

array([[0.86842473, 0.73882943, 0.18256441, 0.71393131, 0.40682883,
        0.18046893, 0.84628519, 0.03862678, 0.89916718, 0.54178183],
       [0.06006419, 0.4916707 , 0.34437923, 0.82372415, 0.67420054,
        0.50015348, 0.59067383, 0.12367067, 0.21447297, 0.26570461],
       [0.01449451, 0.98745477, 0.59927384, 0.73938851, 0.16681307,
        0.51588009, 0.814335  , 0.88258368, 0.99789071, 0.55000773],
       [0.920078  , 0.8123559 , 0.76475592, 0.79566748, 0.70542165,
        0.37186681, 0.66465838, 0.07619476, 0.07189903, 0.69391368],
       [0.17832424, 0.22918357, 0.25651717, 0.25821346, 0.17863596,
        0.77061565, 0.78063544, 0.93637372, 0.4145059 , 0.306239  ],
       [0.26706707, 0.98510857, 0.08175627, 0.28257413, 0.49669418,
        0.36985253, 0.32058002, 0.87185528, 0.8144869 , 0.45371451],
       [0.01323546, 0.4737068 , 0.78055935, 0.19066115, 0.17320972,
        0.79811049, 0.76796913, 0.46855137, 0.38548345, 0.32580784],
       [0.73432911, 0.76111049, 0.5484418

In [88]:
arr18.max()

0.9978907102457347

In [89]:
arr18.min()

0.013235463578915807

27. a = np.array([1,2,3,2,3,4,3,4,5,6]) b = np.array([7,2,10,2,7,4,9,4,9,8])
---
Find the common items between a and b


In [91]:
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])

In [92]:
np.intersect1d(a, b)

array([2, 4])

28. a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])

---
Find the positions where elements of a and b match



In [95]:
np.equal(a, b).nonzero()[0]

array([1, 3, 5, 7], dtype=int64)

29.  names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])  data = np.random.randn(7, 4)

---
Find all the values from array **data** where the values from array **names** are not equal to **Will**


In [111]:
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])
data = np.random.randint(4, size=7)
print(f"Data: {data}")
# data[(names[data] != "Will").nonzero()]
data_filtered = []
for i in range(len(names)):
    if names[i] != "Will":
        data_filtered.append(data[i])
print(f"Filtered Data: {data_filtered}")

Data: [3 2 1 0 1 2 2]
Filtered Data: [3, 2, 0, 2, 2]


30. names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe']) data = np.random.randn(7, 4)

---
Find all the values from array **data** where the values from array **names** are not equal to **Will** and **Joe**



In [112]:
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])
data = np.random.randint(4, size=7)
print(f"Data: {data}")
# data[(names[data] != "Will").nonzero()]
data_filtered = []
for i in range(len(names)):
    if names[i] != "Will" and names[i]!="Joe":
        data_filtered.append(data[i])
print(f"Filtered Data: {data_filtered}")

Data: [0 3 3 1 3 3 1]
Filtered Data: [0, 1]


Difficulty Level **Hard**

31. Create a 2D array of shape 5x3 to contain decimal numbers between 1 and 15.

In [114]:
arr19 = np.arange(1, 16, dtype=float).reshape(5, 3)
arr19

array([[ 1.,  2.,  3.],
       [ 4.,  5.,  6.],
       [ 7.,  8.,  9.],
       [10., 11., 12.],
       [13., 14., 15.]])

32. Create an array of shape (2, 2, 4) with decimal numbers between 1 to 16.

In [115]:
arr20 = np.arange(1, 17, dtype=float).reshape(2, 2, 4)
arr20

array([[[ 1.,  2.,  3.,  4.],
        [ 5.,  6.,  7.,  8.]],

       [[ 9., 10., 11., 12.],
        [13., 14., 15., 16.]]])

33. Swap axes of the array you created in Question 32

In [118]:
np.swapaxes(arr20, 1, 2)

array([[[ 1.,  5.],
        [ 2.,  6.],
        [ 3.,  7.],
        [ 4.,  8.]],

       [[ 9., 13.],
        [10., 14.],
        [11., 15.],
        [12., 16.]]])

34. Create an array of size 10, and find the square root of every element in the array, if the values less than 0.5, replace them with 0

In [141]:
arr21 = np.random.uniform(0, 1, 10)
# arr21
arr21sqrt = np.sqrt(arr21)
for i in range(len(arr21sqrt)):
    if arr21sqrt[i] < 0.5:
        arr21sqrt[i] = 0
arr21sqrt

array([0.81921713, 0.        , 0.90961684, 0.66560266, 0.93069444,
       0.        , 0.50920675, 0.        , 0.5524042 , 0.        ])

35. Create two random arrays of range 12 and make an array with the maximum values between each element of the two arrays

In [147]:
arr22 = np.random.uniform(0, 5, size=12)
arr23 = np.random.uniform(0, 5, size=12)
arr24 = np.maximum(arr22, arr23)
arr24

array([4.34752239, 4.26243789, 4.44250569, 1.97147035, 4.44851789,
       4.97269542, 3.35531164, 2.27814987, 2.93736872, 3.75154227,
       4.01457004, 2.33582774])

36. names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])

---
Find the unique names and sort them out!


In [151]:
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])
np.sort(np.unique(names))

array(['Bob', 'Joe', 'Will'], dtype='<U4')

37. a = np.array([1,2,3,4,5])
b = np.array([5,6,7,8,9])

---
From array a remove all items present in array b



In [152]:
a = np.array([1,2,3,4,5])
b = np.array([5,6,7,8,9])

np.setdiff1d(a, b)

array([1, 2, 3, 4])

38.  Following is the input NumPy array delete column two and insert following new column in its place.

---
sampleArray = numpy.array([[34,43,73],[82,22,12],[53,94,66]]) 


---

newColumn = numpy.array([[10,10,10]])


In [159]:
sampleArray = np.array([[34,43,73],[82,22,12],[53,94,66]]) 
newColumn = np.array([[10,10,10]])

newSampleArray = sampleArray
newSampleArray[1:2, :] = newColumn
newSampleArray

array([[34, 43, 73],
       [10, 10, 10],
       [53, 94, 66]])

39. x = np.array([[1., 2., 3.], [4., 5., 6.]]) y = np.array([[6., 23.], [-1, 7], [8, 9]])


---
Find the dot product of the above two matrix


In [160]:
x = np.array([[1., 2., 3.], [4., 5., 6.]])
y = np.array([[6., 23.], [-1, 7], [8, 9]])
np.dot(x, y)

array([[ 28.,  64.],
       [ 67., 181.]])

40. Generate a matrix of 20 random values and find its cumulative sum

In [163]:
np.cumsum(np.random.uniform(0, 5, 20))

array([ 0.138294  ,  0.60699019,  4.45068618,  8.97220702, 12.15891115,
       16.47152894, 17.52206995, 20.82703781, 21.73698498, 23.76467223,
       24.59681309, 25.26884115, 26.54531889, 28.47386829, 29.87317725,
       30.31786018, 33.77901421, 37.14123593, 39.86005763, 41.35712691])