# Numpy Assignment 2

## Question:1

### Convert a 1D array to a 2D array with 2 rows?

#### Desired output

```python
array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])
```

In [2]:
import numpy as np
np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9]).reshape(2, 5)

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

## Question:2

###  How to stack two arrays vertically?

#### Desired Output::

In [9]:
a = np.arange(0, 10, 1)
b = np.ones(10, dtype=int)
np.vstack((a, b))

array([[0, 1, 2, 3, 4, 5, 6, 7, 8, 9],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1]])

## Question:3

### How to stack two arrays horizontally?

#### Desired Output::

In [12]:
np.hstack((a.reshape(2, 5), b.reshape(2, 5)))

array([[0, 1, 2, 3, 4, 1, 1, 1, 1, 1],
       [5, 6, 7, 8, 9, 1, 1, 1, 1, 1]])

## Question:4

### How to convert an array of arrays into a flat 1d array?

#### Desired Output::

## Question:5

### How to Convert higher dimension into one dimension?

#### Desired Output::

In [15]:
array2d = np.arange(0, 15).reshape(3, 5)
print(array2d)
array2d.flatten()

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]


array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

## Question:6

### Convert one dimension to higher dimension?

#### Desired Output::

```python
array([[ 0, 1, 2],
       [ 3, 4, 5],
       [ 6, 7, 8],
       [ 9, 10, 11],
       [12, 13, 14]])
```

In [17]:
array1d = np.arange(0, 15)
print(array1d)
array1d.reshape(5, 3)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]


array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])

## Question:7

### Create a 5x5 array and find the square of an array?

In [22]:
array5x5 = np.random.rand(5, 5)
np.square(array5x5)

array([[4.22253452e-01, 2.63412849e-01, 6.73234162e-01, 2.34967139e-01,
        4.87616865e-01],
       [5.54475656e-02, 5.81222939e-01, 4.33389199e-01, 3.79924106e-01,
        4.29421172e-01],
       [1.36258876e-01, 7.75506404e-03, 1.78631590e-04, 3.31363904e-01,
        4.76525069e-01],
       [4.83046849e-01, 3.94625240e-01, 5.62969234e-01, 8.61671201e-01,
        3.38303801e-01],
       [7.75267821e-01, 1.74474428e-01, 1.81799785e-01, 9.52993930e-01,
        3.78542101e-01]])

## Question:8

### Create 5x6 an array and find the mean?

In [24]:
array5x6 = np.random.rand(5, 6)
np.mean(array5x6)

0.568482111554922

## Question:9

### Find the standard deviation of the previous array in Q8?

In [25]:
np.std(array5x6)

0.326517731476773

## Question:10

### Find the median of the previous array in Q8?

In [26]:
np.median(array5x6)

0.6572781591629416

## Question:11

### Find the transpose of the previous array in Q8?

In [27]:
array5x6.T

array([[0.31597339, 0.9649338 , 0.67247129, 0.85255542, 0.4966912 ],
       [0.76551387, 0.96957257, 0.46852244, 0.98311928, 0.79973426],
       [0.27352282, 0.98124363, 0.76662296, 0.64208503, 0.14353159],
       [0.21253473, 0.61963943, 0.9746356 , 0.07283169, 0.93039064],
       [0.0775636 , 0.10349851, 0.78801923, 0.71833102, 0.4321385 ],
       [0.90154331, 0.15033916, 0.73915866, 0.23401956, 0.00372614]])

## Question:12

### Create a 4x4 an array and find the sum of diagonal elements?

In [33]:
array4x4 = np.random.rand(4, 4)
print(array4x4)
np.trace(array4x4)

[[0.06239327 0.62791459 0.00416731 0.94016385]
 [0.47533105 0.76010126 0.88439407 0.90283346]
 [0.19569346 0.5722176  0.75682317 0.48468395]
 [0.76592927 0.12220697 0.21532719 0.01441955]]


1.593737244954671

## Question:13

### Find the determinant of the previous array in Q12?

In [34]:
np.linalg.det(array4x4)

0.07432229914193092

## Question:14

### Find the 5th and 95th percentile of an array?

In [39]:
exArray = np.random.randint(25, 100, (4, 4))
print(f"5th Percentile: {np.percentile(exArray, 5)}")
print(f"95th Percentile: {np.percentile(exArray, 95)}")

5th Percentile: 27.5
95th Percentile: 91.25


## Question:15

### How to find if a given array has any null values?

In [48]:
arrayWithNaN = np.array([
    [5, np.nan, 8],
    [2, 0, 1]
])
arrayWithNaN

array([[ 5., nan,  8.],
       [ 2.,  0.,  1.]])

In [50]:
np.isnan(arrayWithNaN).any()

True